# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f033a5b863fc898ae6cdeb6c58fdef1a01c0387c2e05b100045b45218ccdd7ea7112b3809a235a4a3e484c89c711cd8c8546b253a0a1d1b6b3802e426f8d5827

test:
  secret_key_base: bfcc4afffe68efb34c85ffb11e5ba584b9b321abe9c4aa24dad6e18da404b3c73ec85d984ca5161a338631728f90a4ff27b8ff3cf11876c14c8424f3a5e2af4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
